security:
  oauth2:
    client:
      clientId: event-service
      clientSecret: event-secret
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

server:
  context-path: /eventapi
  port: 2121