security:
  oauth2:
    client:
      clientId: example-service
      clientSecret: example-secret
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

server:
  context-path: /example
  port: 2121