zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
      path: /uaa/**
      url: http://localhost:5000
      stripPrefix: false
      sensitiveHeaders:
    example-service:
      path: /example/**
      serviceId: example-service
      stripPrefix: false
      sensitiveHeaders:

server:
  port: 4000