zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
        path: /auth/**
        url: http://localhost:5000
        stripPrefix: false
        sensitiveHeaders:

server:
  port: 4000