zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
      path: /uaa/**
      url: http://auth-service:5000
      stripPrefix: false
      sensitiveHeaders:
    event-service:
      path: /eventapi/**
      serviceId: event-service
      stripPrefix: false
      sensitiveHeaders:
    group-service:
      path: /groupapi/**
      serviceId: group-service
      stripPrefix: false
      sensitiveHeaders:

server:
  port: 4000